name = "fishinge"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"
usage_model = "bundled"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.production]
routes = [
	{ pattern = "fishinge.fitti.io/*", zone_name = "fitti.io" }
]

